# 02.R

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

library("tidyverse")

euler02 <- function() {

n <- 10^4

fibs = vector("list", n)

fibs[1:2] = c(1, 2)

i <- 2

while (fibs[[i]] + fibs[[i-1]] <= 4000000 & i < n) {
  i <- i+1
  fibs[[i]] <- fibs[[i-1]] + fibs[[i - 2]]
}

fibs_dbl <- flatten_dbl(fibs[1:i])
fibs_even <- fibs_dbl[fibs_dbl %% 2 == 0]

sum(fibs_even)
}

euler02()

microbenchmark(
  euler02()
)